class Constants(object):
    INVALID_TOKEN = 'Invalid or expire token'
    UPDATE_PASSWORD = 'The password succefully updated'
    INVALID_EMAIL_PASSWORD = 'Invalid email or password'
    REGISTER_SUCCESS = 'Register Successfully'
    LOGIN_SUCCESS = 'Login Successfully'
    POST_SUCCESS = 'Post Successfully'
    UPDATE_SUCCESS = 'Update Successfully'
    DELETE_SUCCESS = 'Delete Successfully'
    FIRST_REGISTER_EMAIL = 'This email does not exist please first register with this email'
    EMAIL_ALREADY_EXIST = 'This email is already exist please choose another email'
    USER_ALREADY_EXIST = 'This user is already exist please choose another email'
